//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderFurniture.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipments
    {
        public int Id { get; set; }
        public string label { get; set; }
        public string TypeEquipment { get; set; }
        public string Characteristic { get; set; }
        public Nullable<System.DateTime> DateOfPurchase { get; set; }
        public string Name { get; set; }
    
        public virtual TypeEquipment TypeEquipment1 { get; set; }
    }
}
