//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderFurniture.ModelBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrderfurnituredbEntities : DbContext
    {
        public static OrderfurnituredbEntities _context;
        public OrderfurnituredbEntities()
            : base("name=OrderfurnituredbEntities")
        {
        }
        public static OrderfurnituredbEntities GetContext()
        {
            if(_context == null)
            {
                _context = new OrderfurnituredbEntities();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Equipments> Equipments { get; set; }
        public virtual DbSet<Furniture> Furniture { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<SpecificationFurniture> SpecificationFurniture { get; set; }
        public virtual DbSet<SpecificationMaterial> SpecificationMaterial { get; set; }
        public virtual DbSet<SpecificationOperation> SpecificationOperation { get; set; }
        public virtual DbSet<SpecificationUnit> SpecificationUnit { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeEquipment> TypeEquipment { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
