//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderFurniture.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public string Product { get; set; }
        public string Customer { get; set; }
        public string Manager { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
    
        public virtual Product Product1 { get; set; }
        public virtual Users Users { get; set; }
    }
}
