//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderFurniture.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificationMaterial
    {
        public string Product { get; set; }
        public string Material { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Material Material1 { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
