//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderFurniture.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificationOperation
    {
        public string Product { get; set; }
        public string Operation { get; set; }
        public int OrderNumber { get; set; }
        public string TypeEquipment { get; set; }
        public Nullable<System.DateTime> TimeOnOperation { get; set; }
    
        public virtual Product Product1 { get; set; }
        public virtual TypeEquipment TypeEquipment1 { get; set; }
    }
}
